#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AquaBuddy.Resource", IsApplication=true)]

namespace AquaBuddy
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int AddExerciseButton = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int CancelAddExerciseButton = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int MyButton = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int Text2SpeechTest = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int buttonSayIt = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int createExercise = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int editText1 = 2131034130;
			
			// aapt resource value: 0x7f050002
			public const int editTextExercise = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int editTextExerciseDescription = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int gridLayout2 = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int numberpickerDuration = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int radioButtonHigh = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int radioButtonLow = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int radioButtonMedium = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int radioGroupIntensity = 2131034116;
			
			// aapt resource value: 0x7f050016
			public const int seekPitch = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int seekSpeed = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int spinLanguage = 2131034132;
			
			// aapt resource value: 0x7f050010
			public const int testFileList = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int testMusic = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int textView2 = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int textViewDuration = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int exerciseCreate = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FileListLO = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MusicTestLO = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Text2SpeechLO = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int AddExercise = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int CancelAddExercise = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Text2SpeechTest = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int createExercise = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int entertextButton = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int testFileList = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int testmusic = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
